In [20]:
import pandas as pd

In [21]:
room_data = pd.read_csv("U_HOSP.csv")

In [22]:
lst = [2089569,2098703,2098714,2098715,2098843,2098957,2099153,2099234,2099250,2099339,2099414,2099632,2099633,2099945,2100066,2100157,2100174,2098691,2098694,2098698,2098699,2098701,2098704,2098708,2098719,2098727,2098730,2098748,2098838,2099236,2099243,2099244,2099249,2099250,2099251,2099252,2099254,2099259,2099261,2099265,2099274,2099275,2099279,2099280,2099281,2099283,2099285,2099288,2099290,2099293,2099295,2099296,2099298,2099299,2099304,2099305,2099307,2099334,2099335,2099346,2099347,2099348,2099349,2099356,2099357,2099358,2099359,2099363,2099364,2099367,2099372,2099374,2099375,2099415,2099418,2099422,2099451,2099944,2100002,2100052,2100059,2100060,2100062,2100064,2100071,2100084,2100154,2100156,2100159,2100160,2100162,2100168,2100169,2100174,2100175,2100180,2100181,2100184,2100187,2100189,2100192,2100193,2100194,2100197,2100198,2100199,2100200,2100202,2100203,2100204,2100206,2100207,2100208,2100230,2100240,2100731,2100732,2100738,2100741,2104919,2104920,2104921,2104922,2104923,2104925,2104929,2104930,2110960,2110962,2110963,2127298,2127301,2134168,2190785,2190786,2190787,2190788,2190789,2190790,2190791,2190793,2190794,2190795,2190796,2190797]

rmnbrs = pd.DataFrame(lst)
rmnbrs.head()

         0
0  2089569
1  2098703
2  2098714
3  2098715
4  2098843

In [23]:
room_data_filtered = room_data[room_data["rmrecnbr"].isin(lst)][["rmrecnbr", "occdeptlist", "rmnbr"]]
room_data_filtered

      rmrecnbr                             occdeptlist    rmnbr
2      2098691                                     NaN    1A100
5      2098694  MM UHCVC Security Svcs (311640) - 100%    1A201
6      2110960  MM UHCVC Security Svcs (311640) - 100%   1A201A
8      2110962  MM UHCVC Security Svcs (311640) - 100%   1A201D
9      2110963  MM UHCVC Security Svcs (311640) - 100%   1A201F
...        ...                                     ...      ...
3607   2100741   MM Pulmonary Lab Tech (317900) - 100%   B1H268
3608   2100207   MM Pulmonary Lab Tech (317900) - 100%   B1H270
3609   2100208   MM Pulmonary Lab Tech (317900) - 100%   B1H272
3631   2100230                                     NaN  B1H416C
3641   2100240                                     NaN  B1K100M

[141 rows x 3 columns]

In [26]:
writer = pd.ExcelWriter("rooms.xlsx")
room_data_filtered.to_excel(writer, index = False)
writer.close()

In [27]:
filtered_list = [2098691,2098694,2098698,2098699,2098701,2098703,2098704,2098708,2098714,2098715,2098719,2098727,2098730,2098748,2098838,2098843,2098957,2099153,2099234,2099236,2099243,2099244,2099249,2099250,2099251,2099252,2099254,2099259,2099261,2099265,2099274,2099275,2099279,2099280,2099281,2099283,2099285,2099288,2099290,2099293,2099295,2099296,2099298,2099299,2099304,2099305,2099307,2099334,2099335,2099339,2099346,2099347,2099348,2099349,2099356,2099357,2099358,2099359,2099363,2099364,2099367,2099372,2099374,2099375,2099414,2099415,2099418,2099422,2099451,2099632,2099633,2099944,2099945,2100002,2100052,2100059,2100060,2100062,2100064,2100066,2100071,2100084,2100154,2100156,2100157,2100159,2100160,2100162,2100168,2100169,2100174,2100175,2100180,2100181,2100184,2100187,2100189,2100192,2100193,2100194,2100197,2100198,2100199,2100200,2100202,2100203,2100204,2100206,2100207,2100208,2100230,2100240,2100731,2100732,2100738,2100741,2104919,2104920,2104921,2104922,2104923,2104925,2104929,2104930,2110960,2110962,2110963,2127298,2127301,2134168,2190785,2190786,2190787,2190789,2190790,2190791,2190793,2190794,2190795,2190796,2190797]
unfiltered = [2089569,2098703,2098714,2098715,2098843,2098957,2099153,2099234,2099250,2099339,2099414,2099632,2099633,2099945,2100066,2100157,2100174,2098691,2098694,2098698,2098699,2098701,2098704,2098708,2098719,2098727,2098730,2098748,2098838,2099236,2099243,2099244,2099249,2099250,2099251,2099252,2099254,2099259,2099261,2099265,2099274,2099275,2099279,2099280,2099281,2099283,2099285,2099288,2099290,2099293,2099295,2099296,2099298,2099299,2099304,2099305,2099307,2099334,2099335,2099346,2099347,2099348,2099349,2099356,2099357,2099358,2099359,2099363,2099364,2099367,2099372,2099374,2099375,2099415,2099418,2099422,2099451,2099944,2100002,2100052,2100059,2100060,2100062,2100064,2100071,2100084,2100154,2100156,2100159,2100160,2100162,2100168,2100169,2100174,2100175,2100180,2100181,2100184,2100187,2100189,2100192,2100193,2100194,2100197,2100198,2100199,2100200,2100202,2100203,2100204,2100206,2100207,2100208,2100230,2100240,2100731,2100732,2100738,2100741,2104919,2104920,2104921,2104922,2104923,2104925,2104929,2104930,2110960,2110962,2110963,2127298,2127301,2134168,2190785,2190786,2190787,2190788,2190789,2190790,2190791,2190793,2190794,2190795,2190796,2190797]

difference = [item for item in unfiltered if item not in filtered_list]
difference

[2089569, 2190788]